### ISSUE TITLE
Should `esgf missing` return datasets instead of files?

### ISSUE THREAD

**Issue by ScottWales** [ScottWales/arccssive2#10]
Currently `esgf missing` returns file ids. This could be useful for spotting single files missing from a dataset, but in most cases the whole dataset will be downloaded. Having the search be on files may also produce an overwhelming number of matches

**Comment by ScottWales** [comment]
Maybe make use of `--format` flag:

    --format=dataset
    --format=files
    --format=directory
    --format=synda

**Comment by paolap** [comment]
This is probably still an issue mostly for CMIP5 were a dataset-id includes more variables,
so it is not clear in the missing results which variable is missing, which is maybe more easy to solve that the files issue?
In any case synda won't download a file if it's alredy there so it could be sufficient spotting the relevant id from a download point of view

**Comment by ScottWales** [comment]
Return the dataset id and the variable name as two columns
