### ISSUE TITLE
review click common_args

### ISSUE THREAD

**Issue by paolap** [ScottWales/arccssive2#24]
We should make sure we review the query arguments. Here are some thoughts:

I think **product** and **variable_long_name** could be deleted;
 **time_frequency** maybe should be shortened to frequency
**experiment_family** might not make sense anymore while **source_type** (which is type of model ie. AOGM,AMIP) might be much more useful.
There are quite a few args that exists only for CMIP6 maybe we should print a warning when used with CMIP5 and then ignore them in the search

For facets like ensemble which have changed with CMIP6 maybe we should use CMIP6 name and map to cmip5 when user query cmip5, so we do not confuse users with two sets of arguments

--debug
--no-distrib
--replica  Maybe these could all become a flag ? So with default no-debug, no-replica and distrib
change "format" to something else (maybe out_format??) to avoid conflicts and to clarify meaning

**Comment by paolap** [comment]
In my handling -args branch:
 I've eliminated product/variable_long_name
divided args as "common_args" , "cmip5_args" and "cmip6_args"
I call cmip5+common args for CMIP5 search/local/missing
       cmip6_common args for CMIP6 search/local/missing

**Comment by paolap** [comment]
We only have to decide if changing flags for example
--distrib, is_flag=True instead of   --distrib/--no-distrib

**Comment by ScottWales** [comment]
I think it makes it clearer to be able to explicitly enable or disable options, like:

```
Options:
    [ --distrib | --no-distrib ] Distribute search across all ESGF nodes. Default: --distrib
    [ --replica | --no-replica ] Return both original files and replicas. Default: --no-replica
    [ --latest | --all-versions ] Return only the latest version or all of them. Default: --latest
```
