### ISSUE TITLE
combining local and missing

### ISSUE THREAD

**Issue by paolap** [ScottWales/arccssive2#25]
I showed the tool this morning at the meeting and there was a a strong preference for having less subcommands. We also agreed that probably a user would want to know both what's local and what's missing in one go. So they suggested to make that the default and then give the option of choosing only one or the other.

If we do so then local and missing will become "flags" rather then subcommand and automatically we will have less subcommands left.

I will try to implement this first and then see if we can take it a step further and have "nested" commands based on passing a value to the "project" argument. In this way if we add more datasets, like cordex, that potentially need different arguments we can more easily adapt the tool.

**Comment by paolap** [comment]
Changed functionality
I've combined local and missing and added 4 flags to the main "esgf' command
--search will return only the ESGF search results
--local only local files matching the search
--missing dataset-id for files which haven't been downloaded yet and match the search
--request is  a placeholder for when users will be able to request a download
Two subcommands cmip5/cmip6
Ex
esgf --local cmip5 <opt1> <opt2> ...
without any flag
esgf cmip6 <opt1> <opt2> will print both local and missing results

**Comment by ScottWales** [comment]
Is this ok to close @paolap ?
